apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-catalyst-api-v1-sa
  namespace: platform-catalyst-api-v1
  labels:
    app: platform-catalyst-api-v1
    app.kubernetes.io/name: platform-catalyst-api-v1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/platform-catalyst-api-v1-role
